name: "[Demo] Run Scan Action"

on: [push, pull_request,  workflow_dispatch]

jobs:
  test-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        image: "alpine:latest"
        debug: true

  test-directory:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        path: "tests/python"
        debug: true
        severity-cutoff: "negligible"
