name: "[SARIF] Run Scan Action"

on: [push, pull_request]

jobs:
  sarif-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Run the local Scan Action with SARIF generation enabled
      id: scan
      uses: ./
      with:
        image: "debian:8"
        debug: true
        acs-report-enable: true
        #severity-cutoff: "Medium"

    - name: Inspect Generated SARIF
      run: cat ${{ steps.scan.outputs.sarif }}

    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif

  sarif-directory:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Run the local Scan Action with SARIF generation enabled
      id: scan
      uses: ./
      with:
        path: "tests/python"
        debug: true
        acs-report-enable: true
        #severity-cutoff: "Medium"

    - name: Inspect Generated SARIF
      run: cat ${{ steps.scan.outputs.sarif }}
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

